'use client';
import { useEffect, useState } from 'react';
import { StorefrontView, type StoreProduct } from '../../digitize-design-system/storefront';
import { themes, type ThemeName } from '../../digitize-design-system/themes';

type AdminProduct={id:string;name?:string;title?:string;description?:string;price?:string|number;images?:Array<{url:string}>}; type Item={id:string;title?:string;name?:string;description?:string;status?:string};
export default function Preview(){const [theme,setTheme]=useState<ThemeName>('minimal'),[products,setProducts]=useState<StoreProduct[]>([]),[collections,setCollections]=useState<Item[]>([]),[orders,setOrders]=useState<Item[]>([]),[view,setView]=useState<'home'|'collections'|'products'|'orders'>('home'),[error,setError]=useState('');const scope=()=>{const p=new URLSearchParams(location.search);return{bid:p.get('bid'),storeId:p.get('storeId'),token:localStorage.getItem('digitize_token')}};
useEffect(()=>{const {bid,storeId,token}=scope();if(!bid||!storeId||!token){setError('Open this preview from the business admin.');return;}const headers={Authorization:`Bearer ${token}`},base=`/api/business/${bid}/stores/${storeId}`;Promise.all([fetch(`${base}/store`,{headers}),fetch(`${base}/products`,{headers}),fetch(`${base}/collections`,{headers}),fetch(`${base}/orders`,{headers})]).then(async([s,p,c,o])=>{if(!s.ok||!p.ok)throw new Error('You are not allowed to preview this store');const settings=await s.json(),listed=await p.json() as AdminProduct[];setTheme(settings.theme??'minimal');setCollections(c.ok?await c.json():[]);setOrders(o.ok?await o.json():[]);const withImages=await Promise.all(listed.map(async product=>{const r=await fetch(`${base}/products/${product.id}/images`,{headers});return{...product,images:r.ok?await r.json():[]};}));setProducts(withImages.map(p=>({id:p.id,title:p.name??p.title??'Untitled product',description:p.description,price:p.price,imageUrl:p.images?.[0]?.url})));}).catch(reason=>setError(reason.message));},[]);
async function selectTheme(next:ThemeName){setTheme(next);const {bid,storeId,token}=scope();if(!bid||!storeId||!token)return;const r=await fetch(`/api/business/${bid}/stores/${storeId}/store`,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({theme:next})});if(!r.ok)setError('The theme could not be saved.');}
const nav=<>{[['home','Home'],['collections','Collections'],['products','Products'],['orders','Orders']].map(([key,label])=><a key={key} className="nav-link" href={`#${key}`} onClick={event=>{event.preventDefault();setView(key as typeof view);}}>{label}</a>)}</>;
const visible=view==='home'?products.slice(0,3):view==='products'?products:[];return error?<p style={{padding:24}}>{error}</p>:<div className="preview-shell"><StorefrontView storeName="Store preview" theme={theme} products={visible} navigation={nav} headerAction={<select value={theme} onChange={e=>selectTheme(e.target.value as ThemeName)} aria-label="Store theme">{themes.map(t=><option key={t.name} value={t.name}>{t.label}</option>)}</select>}/>{view==='collections'&&<section className="preview-panel"><h2>Collections</h2>{collections.map(c=><article key={c.id}><strong>{c.title??c.name??'Collection'}</strong><p>{c.description??''}</p></article>)}</section>}{view==='orders'&&<section className="preview-panel"><h2>Orders</h2>{orders.map(o=><article key={o.id}><strong>{o.name??o.title??`Order ${o.id.slice(0,8)}`}</strong><p>{o.status??'PENDING'}</p></article>)}</section>}</div>}
