'use client';
import { useEffect, useState } from 'react';
import { StorefrontView, type StoreProduct } from '../../digitize-design-system/storefront';
import type { ResolvedTheme } from '../../digitize-design-system/themes';

type Product={id:string;name?:string;title?:string;description?:string;price?:string|number};
const fallback:ResolvedTheme={name:'minimal',version:2,configuration:{'--store-bg':'#f7f6f1','--store-ink':'#17211d','--store-accent':'#e5ff62','--store-muted':'#66716a','--store-line':'#d9ddd5','--home-columns':'3','--products-columns':'3','--collections-columns':'3','--orders-columns':'1','--card-border':'1px','--card-radius':'8px'}};
const controls=[['--home-columns','Home columns'],['--products-columns','Products columns'],['--collections-columns','Collection columns'],['--orders-columns','Order columns'],['--card-border','Border width'],['--card-radius','Corner roundness']];

export default function Preview(){
 const [theme,setTheme]=useState<ResolvedTheme>(fallback),[available,setAvailable]=useState<ResolvedTheme[]>([]),[products,setProducts]=useState<StoreProduct[]>([]),[customizing,setCustomizing]=useState(false),[message,setMessage]=useState('');
 const scope=()=>{const p=new URLSearchParams(location.search);return{bid:p.get('bid'),storeId:p.get('storeId'),token:localStorage.getItem('digitize_token')}};
 const save=async(next:ResolvedTheme)=>{const {bid,storeId,token}=scope();if(!bid||!storeId||!token)return;const r=await fetch(`/api/business/${bid}/stores/${storeId}/themes/current`,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(next)});setMessage(r.ok?'Theme configuration saved.':'Unable to save theme configuration.');};
 useEffect(()=>{const {bid,storeId,token}=scope();if(!bid||!storeId||!token){setMessage('Open this preview from the business admin.');return;}const h={Authorization:`Bearer ${token}`},base=`/api/business/${bid}/stores/${storeId}`;Promise.all([fetch(`${base}/themes`,{headers:h}),fetch(`${base}/themes/current`,{headers:h}),fetch(`${base}/products`,{headers:h})]).then(async([a,b,c])=>{setAvailable(await a.json());setTheme(await b.json());const list=await c.json() as Product[];const cards=await Promise.all(list.map(async p=>{const images=await fetch(`${base}/products/${p.id}/images`,{headers:h});const gallery=images.ok?await images.json():[];return{id:p.id,title:p.name??p.title??'Untitled product',description:p.description,price:p.price,imageUrl:gallery[0]?.url} as StoreProduct;}));setProducts(cards);}).catch(()=>setMessage('Unable to load preview.'));},[]);
 const choose=(value:string)=>{const [name,version]=value.split(':');const next=available.find(t=>t.name===name&&t.version===Number(version));if(next){setTheme(next);void save(next);}};
 const change=(key:string,value:string)=>setTheme({...theme,configuration:{...theme.configuration,[key]:value}});
 const nav=<><a className="nav-link" href="#">Home</a><a className="nav-link" href="#">Collections</a><a className="nav-link" href="#">Products</a><a className="nav-link" href="#">Orders</a></>;
 return <><StorefrontView storeName="Store preview" theme={theme} products={products.slice(0,3)} navigation={nav} headerAction={<><select value={`${theme.name}:${theme.version}`} onChange={event=>choose(event.target.value)}>{available.map(t=><option key={`${t.name}:${t.version}`} value={`${t.name}:${t.version}`}>{t.name} v{t.version}</option>)}</select><button onClick={()=>setCustomizing(true)}>Customize</button></>}/>{customizing&&<section className="preview-panel"><h2>Customize theme</h2><div className="theme-controls">{controls.map(([key,label])=><label key={key}>{label}<input value={theme.configuration[key]??''} onChange={event=>change(key,event.target.value)}/></label>)}</div><p><button onClick={()=>void save(theme)}>Save configuration</button><button className="secondary" onClick={()=>setCustomizing(false)}>Close</button></p>{message&&<p>{message}</p>}</section>}</>;
}
