'use client';
import { FormEvent, useEffect, useState, type CSSProperties } from 'react';
import { StorefrontView, type StoreProduct } from '../../digitize-design-system/storefront';
import { resolvedThemeStyle, type ResolvedTheme } from '../../digitize-design-system/themes';

type Product={id:string;data:Record<string,unknown>;images:Array<{url:string}>};
type Collection={id:string;data:Record<string,unknown>;images:Array<{url:string}>};
type Order={id:string;data:Record<string,unknown>;createdAt:string};
type RazorpayResponse={razorpay_order_id:string;razorpay_payment_id:string;razorpay_signature:string};
declare global { interface Window { Razorpay:new(options:Record<string,unknown>)=>{open:()=>void}; } }

const apiUrl=process.env.NEXT_PUBLIC_CUSTOMER_API_URL??'';
const fallback:ResolvedTheme={name:'simple-light',version:1,configuration:{'--store-bg':'#f7f7f5','--store-ink':'#181a18','--store-accent':'#dff45f','--store-muted':'#697069','--store-line':'#dedfda','--home-columns':'3','--products-columns':'3','--collections-columns':'3','--orders-columns':'1','--card-border':'1px','--card-radius':'8px'}};
const viewProduct=(product:Product):StoreProduct=>({id:product.id,title:String(product.data.name??product.data.title??'Untitled product'),description:String(product.data.description??''),price:product.data.price as string|number|undefined,imageUrl:product.images[0]?.url});

export default function Storefront(){
 const [name,setName]=useState('Digitize'),[theme,setTheme]=useState<ResolvedTheme>(fallback),[products,setProducts]=useState<Product[]>([]),[collections,setCollections]=useState<Collection[]>([]),[orders,setOrders]=useState<Order[]>([]);
 const [view,setView]=useState<'home'|'collections'|'products'|'orders'>('home'),[cart,setCart]=useState<Product[]>([]),[token,setToken]=useState(''),[auth,setAuth]=useState(false),[register,setRegister]=useState(false);
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[customerName,setCustomerName]=useState(''),[paymentEnabled,setPaymentEnabled]=useState(false),[paying,setPaying]=useState(false),[notice,setNotice]=useState('');

 useEffect(()=>{const saved=localStorage.getItem('digitize_customer_token');if(saved)setToken(saved);Promise.all([fetch(`${apiUrl}/api/public/context`).then(response=>response.json()),fetch(`${apiUrl}/api/public/products`).then(response=>response.json()),fetch(`${apiUrl}/api/public/collections`).then(response=>response.json())]).then(([context,productList,collectionList])=>{setName(context.name);setTheme(context.theme??fallback);setPaymentEnabled(Boolean(context.payments?.razorpay));document.documentElement.dataset.storeLogo=context.logoUrl??'';setProducts(productList);setCollections(collectionList);}).catch(()=>setNotice('The store is unavailable right now.'));},[]);
 const add=(item:StoreProduct)=>{const product=products.find(value=>value.id===item.id);if(product)setCart(items=>[...items,product]);};
 const count=cart.length,total=cart.reduce((sum,item)=>sum+Number(item.data.price??0),0);
 const showOrders=async()=>{if(!token){setAuth(true);return;}setView('orders');const response=await fetch(`${apiUrl}/api/public/orders`,{headers:{Authorization:`Bearer ${token}`}});if(response.ok)setOrders(await response.json());};
 async function login(event:FormEvent){event.preventDefault();const response=await fetch(`${apiUrl}/api/public/customers/${register?'register':'login'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(register?{name:customerName,email,password}:{email,password})});const data=await response.json();if(!response.ok)return setNotice(data.message??'Could not sign in');localStorage.setItem('digitize_customer_token',data.accessToken);setToken(data.accessToken);setAuth(false);}
 async function loadCheckout(){if(window.Razorpay)return true;return new Promise<boolean>(resolve=>{const script=document.createElement('script');script.src='https://checkout.razorpay.com/v1/checkout.js';script.onload=()=>resolve(true);script.onerror=()=>resolve(false);document.body.appendChild(script);});}
 async function checkout(){if(!token){setAuth(true);return;}if(!paymentEnabled)return setNotice('Online payments are not configured yet.');setPaying(true);setNotice('');try{if(!await loadCheckout())throw new Error('Unable to load secure checkout.');const response=await fetch(`${apiUrl}/api/public/payments/razorpay/order`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({items:cart.map(product=>({productId:product.id,quantity:1}))})});const payment=await response.json();if(!response.ok)throw new Error(payment.message??'Unable to start payment.');new window.Razorpay({key:payment.keyId,amount:payment.amount,currency:payment.currency,name,description:`Order ${payment.orderId.slice(0,8)}`,order_id:payment.razorpayOrderId,prefill:payment.customer,theme:{color:theme.configuration['--store-ink']},handler:async(result:RazorpayResponse)=>{const verification=await fetch(`${apiUrl}/api/public/payments/razorpay/verify`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({orderId:payment.orderId,razorpayOrderId:result.razorpay_order_id,razorpayPaymentId:result.razorpay_payment_id,razorpaySignature:result.razorpay_signature})});if(verification.ok){setCart([]);setNotice('Payment successful. Your order is confirmed.');}else setNotice('Payment received; confirmation is pending.');setPaying(false);},modal:{ondismiss:()=>setPaying(false)}}).open();}catch(error){setNotice(error instanceof Error?error.message:'Unable to start payment.');setPaying(false);}}

 const nav=<>{[['home','Home'],['collections','Collections'],['products','Products']].map(([key,label])=><a key={key} className="nav-link" href={`#${key}`} onClick={event=>{event.preventDefault();setView(key as typeof view);}}>{label}</a>)}<a className="nav-link" href="#orders" onClick={event=>{event.preventDefault();void showOrders();}}>Orders</a></>;
 const visible=view==='home'?products.slice(0,3):view==='products'?products:[];
 return <div style={resolvedThemeStyle(theme) as CSSProperties}>
  <StorefrontView storeName={name} theme={theme} products={visible.map(viewProduct)} cartCount={count} navigation={nav} onAdd={view==='home'||view==='products'?add:undefined} currencySymbol="₹" headerAction={<button className="account-button" onClick={()=>token?(localStorage.removeItem('digitize_customer_token'),setToken('')):setAuth(true)}>{token?'Sign out':'Sign in'}</button>}/>
  {view==='collections'&&<section className="content-panel"><h2>Collections</h2><div className="collection-grid">{collections.map(collection=><article className="collection-card" key={collection.id}>{collection.images[0]?.url&&<img src={collection.images[0].url} alt=""/>}<h3>{String(collection.data.title??'Collection')}</h3><p>{String(collection.data.description??'')}</p></article>)}</div></section>}
  {view==='orders'&&<section className="content-panel"><h2>Your orders</h2>{orders.map(order=><article className="order-card" key={order.id}><strong>Order {order.id.slice(0,8)}</strong><span>{String(order.data.paymentStatus??order.data.status??'PENDING')}</span></article>)}</section>}
  {notice&&<p className="notice">{notice}</p>}
  <aside className="cart"><h2>Your cart</h2><p className="muted">{count?`${count} item${count===1?'':'s'} · ₹${total.toFixed(2)}`:'Your cart is empty.'}</p>{paymentEnabled&&count>0&&<div className="payment-method"><span>UPI</span><small>Intent or QR via Razorpay</small></div>}<button disabled={!count||paying} onClick={checkout}>{paying?'Opening secure checkout…':paymentEnabled?`Pay ₹${total.toFixed(2)}`:'Payments unavailable'}</button></aside>
  {auth&&<div className="modal"><form onSubmit={login}><button type="button" className="close" onClick={()=>setAuth(false)}>×</button><h2>{register?'Create account':'Sign in'}</h2>{register&&<input placeholder="Your name" value={customerName} onChange={event=>setCustomerName(event.target.value)} required/>}<input type="email" placeholder="Email" value={email} onChange={event=>setEmail(event.target.value)} required/><input type="password" placeholder="Password" value={password} onChange={event=>setPassword(event.target.value)} required/><button>{register?'Create account':'Sign in'}</button><button className="link" type="button" onClick={()=>setRegister(value=>!value)}>{register?'Sign in instead':'Create an account'}</button></form></div>}
 </div>;
}
