'use client';
import { FormEvent, useEffect, useMemo, useState, type CSSProperties } from 'react';
import { StorefrontView, type StoreProduct } from '../../digitize-design-system/storefront';
import { themeStyle, type ThemeName } from '../../digitize-design-system/themes';

type Product = { id:string; data:Record<string, unknown>; images:Array<{url:string}> };
type CartItem = { product: Product; quantity:number };
type Collection = { id:string; data:Record<string,unknown>; images:Array<{url:string}> };
type Order = { id:string; data:Record<string,unknown>; createdAt:string };
const apiUrl = process.env.NEXT_PUBLIC_CUSTOMER_API_URL ?? '';
const toViewProduct = (product: Product): StoreProduct => ({ id: product.id, title: String(product.data.name ?? product.data.title ?? 'Untitled product'), description: String(product.data.description ?? ''), price: product.data.price as string | number | undefined, imageUrl: product.images[0]?.url });

export default function Storefront() {
  const [storeName,setStoreName] = useState('Digitize'), [theme,setTheme] = useState<ThemeName>('minimal'), [products,setProducts] = useState<Product[]>([]), [collections,setCollections] = useState<Collection[]>([]), [orders,setOrders] = useState<Order[]>([]), [view,setView] = useState<'home'|'collections'|'products'|'orders'>('home'), [cart,setCart] = useState<CartItem[]>([]), [token,setToken] = useState(''), [showAuth,setShowAuth] = useState(false), [registerMode,setRegisterMode] = useState(false), [email,setEmail] = useState(''), [password,setPassword] = useState(''), [name,setName] = useState(''), [notice,setNotice] = useState('');
  useEffect(() => { const saved=localStorage.getItem('digitize_customer_token'); if(saved)setToken(saved); Promise.all([fetch(`${apiUrl}/api/public/context`).then(r=>r.json()),fetch(`${apiUrl}/api/public/products`).then(r=>r.json()),fetch(`${apiUrl}/api/public/collections`).then(r=>r.json())]).then(([context,items,groups])=>{setStoreName(context.name);setTheme(context.theme ?? 'minimal');setProducts(items);setCollections(groups);}).catch(()=>setNotice('The store is unavailable right now.')); }, []);
  const count=useMemo(()=>cart.reduce((sum,item)=>sum+item.quantity,0),[cart]);
  const add=(view:StoreProduct)=>setCart(items=>{const product=products.find(item=>item.id===view.id); if(!product)return items; const existing=items.find(item=>item.product.id===product.id); return existing?items.map(item=>item.product.id===product.id?{...item,quantity:item.quantity+1}:item):[...items,{product,quantity:1}];});
  async function authenticate(event:FormEvent) { event.preventDefault(); const response=await fetch(`${apiUrl}${registerMode?'/api/public/customers/register':'/api/public/customers/login'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(registerMode?{name,email,password}:{email,password})}); const result=await response.json(); if(!response.ok)return setNotice(result.message ?? 'Could not sign in'); localStorage.setItem('digitize_customer_token',result.accessToken); setToken(result.accessToken);setShowAuth(false);setNotice('You are signed in and can place your order.'); }
  async function checkout() { if(!cart.length)return; if(!token){setShowAuth(true);return;} const response=await fetch(`${apiUrl}/api/public/orders`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({items:cart.map(item=>({productId:item.product.id,quantity:item.quantity}))})}); const result=await response.json(); if(!response.ok)return setNotice(result.message ??'Could not place order');setCart([]);setNotice(`Order ${result.id} has been placed.`); }
  const showOrders=async()=>{if(!token){setShowAuth(true);return;}setView('orders');const response=await fetch(`${apiUrl}/api/public/orders`,{headers:{Authorization:`Bearer ${token}`}});if(response.ok)setOrders(await response.json());};
  const navigation=<>{[['home','Home'],['collections','Collections'],['products','Products']].map(([key,label])=><a key={key} className="nav-link" href={`#${key}`} onClick={event=>{event.preventDefault();setView(key as typeof view);}}>{label}</a>)}<a className="nav-link" href="#orders" onClick={event=>{event.preventDefault();void showOrders();}}>Orders</a></>;
  const visible=view==='home'?products.slice(0,3):view==='products'?products:[];
  return <div style={themeStyle(theme) as CSSProperties}><StorefrontView storeName={storeName} theme={theme} products={visible.map(toViewProduct)} cartCount={count} onAdd={view!=='collections'&&view!=='orders'?add:undefined} navigation={navigation} headerAction={<button className="account-button" onClick={()=>token?(localStorage.removeItem('digitize_customer_token'),setToken(''),setNotice('Signed out.')):setShowAuth(true)}>{token?'Sign out':'Sign in'}</button>}/>{view==='collections'&&<section className="content-panel"><h2>Collections</h2><div className="collection-grid">{collections.map(collection=><article className="collection-card" key={collection.id}>{collection.images[0]?.url&&<img src={collection.images[0].url} alt=""/>}<h3>{String(collection.data.title??'Collection')}</h3><p>{String(collection.data.description??'')}</p></article>)}</div></section>}{view==='orders'&&<section className="content-panel"><h2>Your orders</h2>{orders.length?orders.map(order=><article className="order-card" key={order.id}><strong>Order {order.id.slice(0,8)}</strong><span>{String(order.data.status??'PENDING')}</span><p>{new Date(order.createdAt).toLocaleDateString()}</p></article>):<p>Sign in to view your order history.</p>}</section>}{notice&&<p className="notice">{notice}</p>}<aside className="cart"><h2>Your cart</h2>{cart.length?cart.map(item=><p key={item.product.id}>{String(item.product.data.name ?? item.product.data.title)} × {item.quantity}</p>):<p className="muted">Your cart is empty.</p>}<button disabled={!cart.length} onClick={checkout}>Place order</button><small>Ordering requires a customer account.</small></aside>{showAuth&&<div className="modal"><form onSubmit={authenticate}><button type="button" className="close" onClick={()=>setShowAuth(false)}>×</button><h2>{registerMode?'Create account':'Sign in'}</h2>{registerMode&&<input placeholder="Your name" value={name} onChange={e=>setName(e.target.value)} required/>}<input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" minLength={8} placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><button>{registerMode?'Create account':'Sign in'}</button><button className="link" type="button" onClick={()=>setRegisterMode(value=>!value)}>{registerMode?'Already have an account? Sign in':'New here? Create an account'}</button></form></div>}</div>;
}
