apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: digitize-admin-api
    newName: IMAGE_REGISTRY_PLACEHOLDER/digitize-admin-api
    newTag: dev-initial
  - name: digitize-customer-api
    newName: IMAGE_REGISTRY_PLACEHOLDER/digitize-customer-api
    newTag: dev-initial
  - name: digitize-admin-ui
    newName: IMAGE_REGISTRY_PLACEHOLDER/digitize-admin-ui
    newTag: dev-initial
  - name: digitize-ui
    newName: IMAGE_REGISTRY_PLACEHOLDER/digitize-ui
    newTag: dev-initial
  - name: digitize-preview
    newName: IMAGE_REGISTRY_PLACEHOLDER/digitize-preview
    newTag: dev-initial
